 This is the production variant of
# docker deployment
version: '3'
services:
  app:
    ports:
      - 8080:8080
    links:
      - database
    depends_on:
      - database
    env_file: ./env-development.env
    environment:
      - NODE_ENV=development
      - MONGO_HOST=database
      - MONGO_DB=litnite-development

  database:
    image: mongo
    volumes:
      - ./data/db:/data/db
    restart: always
    ports:
      - "27017:27017"

  nginx: 
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./configurations/nginx.conf:/etc/nginx/conf.d/default.conf
